### ISSUE TITLE
Compatibility error with JupyterLab 3.0

### ISSUE THREAD

**Issue by AdrianSanchezLopez** [2i2c-org/jupyter-launcher-shortcuts#12]
Hi there! this extensions was working great until the realease of JupyterLab > 3.0.0
I'm getting the following error when installing it:
`Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.3 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.2 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/launcher
See the log file for details:  /tmp/jupyterlab-debug-lc_72nit.log
The command '/bin/bash -o pipefail -c jupyter labextension install @jupyterlab/server-proxy jupyterlab-launcher-shortcuts' returned a non-zero code: 1`

Could this extension be adjusted to support the latest JupyterLab? thanks!!

**Comment by tristanlt** [comment]
Hi ! Same here.

Any chance this great product be upgraded to JupyterLab 3+ ?
(no js competence aboard, sorry can't PR)

Many thanks !

**Comment by tristanlt** [comment]
Dear @yuvipanda 
I've released labextension on npm and pushed modification on GH.

@AdrianSanchezLopez this extension is now usable with Jupyterlab 3

Best regards,
Tristan

**Comment by AdrianSanchezLopez** [comment]
Awesome! will test it thanks  @tristanlt!
