### ISSUE TITLE
New pip release?

### ISSUE THREAD

**Issue by VincentKetelaars** [2i2c-org/jupyter-launcher-shortcuts#20]
The last release on pypi (https://pypi.org/project/jupyter-launcher-shortcuts/) is from 2019. Is it possible to get a new release for the latest master?

In particular I'm interested in getting https://github.com/yuvipanda/jupyter-launcher-shortcuts/commit/d1085096ffbba5354dff3c4bc801f4f8dfd4bc00 released.

Thanks in advance!

**Comment by maresb** [comment]
@yuvipanda
![image](https://user-images.githubusercontent.com/15216687/174438353-d184ba1e-0035-4e6c-ae3c-24e7518bae32.png)

**Comment by aberey** [comment]
+1 can we please get the latest version in pypi

**Comment by consideRatio** [comment]
v4.0.3 is now released to PyPI and NPM and should work with jupyterlab 4+, but not notebook v7 yet (tracked in #25) or older versions of the classical notebook UI.
