### ISSUE TITLE
Installation on JL 2.x returns incompatibility issues

### ISSUE THREAD

**Issue by michalrudko** [2i2c-org/jupyter-launcher-shortcuts#9]
I was trying to install this plugin in both JupyterLab 2.2.8 and 2.1.5 venvs by first 
`pip install jupyter-launcher-shortcuts` and then `sudo jupyter labextension install jupyterlab-launcher-shortcuts`however in both cases received incompatibility issues respectively:
```Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.2.5 <2.3.0          >=0.19.1 <0.20.0@jupyterlab/application
>=2.2.5 <2.3.0          >=0.19.1 <0.20.0@jupyterlab/launcher
```
```
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.2 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/application
>=2.1.1 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/launcher
```
Is it a known issue or am I doing something wrong?

**Comment by fabricebrito** [comment]
I'd also love to use this extension on JupyterLab.

**Comment by BobCashStory** [comment]
it's released !

**Comment by michalrudko** [comment]
> it's released !

Released, however still running into incompatibility issues (see description above). Or am I doing something wrong?
